services:

  # purrfect pal main web-app
  main-app:
    build: ./main-app
    container_name: main-app-c
    
  # MySQL Database
  db:
    image: manojshrees/purrfectpalstudio-db:latest
    container_name: db-c
    ports:
      - "3306:3306"
    restart: unless-stopped # Automatically restart the container if it stops
    volumes:
      - mysql_data:/var/lib/mysql

  # Node.js Backend
  backend:
    image: manojshrees/purrfectpalstudio-backend:latest
    container_name: backend-c
    ports:
      - "8080:8080"
    restart: unless-stopped  # Automatically restart the container if it stops
    depends_on:
      - db

  # Nginx Frontend
  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    ports:
      - "80:80"  # Nginx container will bind port 80 on the host to its port 80 (only this container)
      - "443:443"  # Nginx container will bind port 443 on the host to its port 443 (only this container)
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - ./certs:/etc/ssl/certs:ro
      - ./main-app/dist:/usr/share/nginx/html

    depends_on:
      - main-app
      - db 
      - backend

# Volumes for persistent data
volumes:
  mysql_data: