version: '3.8'

services:
  webhook:
    image: almir/webhook
    container_name: webhook-listener
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock    # access to host docker
      - ../production-purrfect-pal-studio:/app/production-purrfect-pal-studio
      - ./hooks.json:/etc/webhook/hooks.json
    networks:
      - pps-network
    command: -hooks=/etc/webhook/hooks.json -port 3000 -verbose
    ports:
      - 3000:3000   # Can use NGINX reverse proxy instead


networks:
  pps-network:
    driver: bridge
